# Generated by Django 5.0.4 on 2024-10-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Talle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=5)),
            ],
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='foto',
            new_name='imagen_principal',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='color',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='talle',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_secundaria_1',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_secundaria_2',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_secundaria_3',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='colores',
            field=models.ManyToManyField(to='ecommerce.color'),
        ),
        migrations.AddField(
            model_name='producto',
            name='talles',
            field=models.ManyToManyField(to='ecommerce.talle'),
        ),
    ]
