# Generated by Django 5.0.4 on 2024-10-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_style',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
