# Generated by Django 5.0.4 on 2024-10-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_color_color_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalleIndumentaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=5)),
            ],
        ),
        migrations.RenameModel(
            old_name='Talle',
            new_name='TalleCalzado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='talles',
        ),
        migrations.AddField(
            model_name='producto',
            name='talles_calzado',
            field=models.ManyToManyField(blank=True, null=True, to='ecommerce.tallecalzado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('indumentaria', 'Indumentaria'), ('calzado', 'Calzado')], default='indumentaria', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='talles_indumentaria',
            field=models.ManyToManyField(blank=True, null=True, to='ecommerce.talleindumentaria'),
        ),
    ]
