# Generated by Django 5.0.4 on 2024-10-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_talleindumentaria_rename_talle_tallecalzado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('novedad', 'Novedad'), ('destacado', 'Destacado'), ('sale', 'Sale')], max_length=20, null=True),
        ),
    ]
