# Generated by Django 5.0.4 on 2024-11-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_marca_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='genero',
            field=models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer'), ('niños', 'Niños'), ('unisex', 'Unisex')], max_length=20),
        ),
    ]
