# Generated by Django 5.0.4 on 2024-11-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_alter_producto_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('indumentaria', 'Indumentaria'), ('calzado', 'Calzado'), ('accesorios', 'Accesorios')], default='indumentaria', max_length=20),
        ),
    ]
