# Generated by Django 5.0.4 on 2024-11-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_producto_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(blank=True, choices=[('novedades', 'Novedades'), ('destacados', 'Destacados'), ('sale', 'Sale')], max_length=20, null=True),
        ),
    ]
