# Generated by Django 5.0.4 on 2024-11-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_alter_producto_talles_accesorios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talleaccesorio',
            name='nombre',
            field=models.CharField(max_length=11),
        ),
    ]
