# Generated by Django 5.0.4 on 2024-11-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_alter_talleaccesorio_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='talles_accesorios',
            field=models.ManyToManyField(blank=True, null=True, to='ecommerce.talleaccesorio'),
        ),
    ]
