# Generated by Django 5.0.4 on 2024-11-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_alter_producto_talles_accesorios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_style',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
