# Generated by Django 5.0.4 on 2025-03-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carroitem',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carroitem',
            name='talle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
